### ISSUE TITLE
Analista  de Infraestrutura Big Data 

### ISSUE THREAD

**Issue by Sueli321** [onurakpolat/awesome-bigdata#192]
Experiência em projetos de infraestrutura. Conhecer o ecossistema que compõe o cluster Hadoop. Atuar com a implantação e definição da solução de ambientes de infraestrutura. Administração Linux e redes, suporte diferenciado para área de desenvolvimento, administração de ambiente produtivo e implementação de micro projetos. Atuar com permissões de segurança, analisar e melhorar a execução das Query. Atuar com banco dados relacionais, troubleshooting, tunning, file systems, Adm Yarn. Análise do sistema operacional e banco de dados, análise de performance. Atuar com Big Data, Hadoop, HBase, Pentaho, MongoDB, HortonWorks e Spark. Perfil generalista.
Benefícios: Assistência Médica / Medicina em grupo, Seguro de vida em grupo, Tíquete-refeição, Vale-transporte
Regime de contratação: CLT (Efetivo)
Horário: De Segunda a Sexta.
Informações adicionais: Local de atuação: Berrini - SP / Santana de Parnaíba.

Interessados enviar cv para: sueli.patricio@triadsystems.com.br

**Comment by amorskoy** [comment]
Spammer.

**Comment by koconder** [comment]
Reported as spam and closed
