### ISSUE TITLE
Consider Spark with Java

### ISSUE THREAD

**Issue by jgperrin** [onurakpolat/awesome-bigdata#195]
Hello,

Please consider adding “Spark with Java” to your awesome list.

* [Spark with Java](https://www.manning.com/books/spark-with-java) - New book on Spark in Manning's Early Access Program (MEAP) with a very strong focus on Java, targeted towards software and data engineers. The author focuses on developing existing skills rather than learning Spark, Scala, and Hadoop at the same time, making Big Data easier to learn. You can find the accompanying GitHub repositories [here](https://github.com/topics/sparkwithjava).

Thanks!

**Comment by koconder** [comment]
Added as requested
