### ISSUE TITLE
SparkJava

### ISSUE THREAD

**Issue by ameet20** [onurakpolat/awesome-bigdata#220]
Please add “Spark with Java” to your awesome list.

SparkJava - New book on Spark in Manning's Early Access Program (MEAP) with a very strong focus on Java, targeted towards software and data engineers. The author focuses on developing existing skills rather than learning Spark, Scala, and Hadoop at the same time, making Big Data easier to learn. You can find the accompanying GitHub repositories here.

**Comment by cricket007** [comment]
Duplicates #195
