### ISSUE TITLE
Could you update lastest Paper about Bigdata?

### ISSUE THREAD

**Issue by vkingnew** [onurakpolat/awesome-bigdata#228]
this part is wonderful   "Interesting Papers",could you update this part since 2016 ?
And as so far，many new big data framework updated，could you update too.

**Comment by koconder** [comment]
@vkingnew feel to make suggestions for me to merge. Someone has added link to another "awesome" list to papers.

**Comment by vkingnew** [comment]
Merge it is better,the search key world "awesome-bigdata" is often searched in github.
