### ISSUE TITLE
Add TDengine, a new big data platform

### ISSUE THREAD

**Issue by StoneT2000** [onurakpolat/awesome-bigdata#240]
Hi, can TDengine be added? It is a recently open sourced big data platform, fairly popular and got 6k stars in about a week within its release. This is the github repo: [https://github.com/taosdata/TDengine](https://github.com/taosdata/TDengine) 

Quoting the repo, 
“TDengine is an open-sourced big data platform under GNU AGPL v3.0, designed and optimized for the Internet of Things (IoT), Connected Cars, Industrial IoT, and IT Infrastructure and Application Monitoring. Besides the 10x faster time-series database, it provides caching, stream computing, message queuing and other functionalities to reduce the complexity and cost of development and operation.”

**Comment by koconder** [comment]
@StoneT2000 feel free to add a pull request, closing issue.
