### ISSUE TITLE
Add TileDB, SciDB and SciDFS

### ISSUE THREAD

**Issue by skanskan** [onurakpolat/awesome-bigdata#251]
Hello.

There are other databases aimed to work with very large databases for fast scientific computation:

TileDB
https://tiledb.io/

SciDB
https://www.paradigm4.com/scidb-database-for-21st-century/

SciDFS
https://www.researchgate.net/publication/325420010_SciDFS_An_In-Situ_Processing_System_for_Scientific_Array_Data_Based_on_Distributed_File_System

**Comment by koconder** [comment]
@skanskan feel free to add a PR, closing issue.
