### ISSUE TITLE
How-to article about AWS Timestream - The new Time Series database from AWS.

### ISSUE THREAD

**Issue by RichardSilveira** [onurakpolat/awesome-bigdata#279]
Hi, let me know if this addition makes sense for you:
https://itnext.io/how-to-begin-with-the-amazon-timestream-in-5-simple-steps-19c129040d9c

This time series is awesome and help a lot who is new in this field, I wrote an article to help who is starting on this world, also who would like to test this new AWS managed time-series database

**Comment by onurakpolat** [comment]
Could you please create a PR?
