### ISSUE TITLE
Oracle Database as NewSQL?

### ISSUE THREAD

**Issue by davidlday** [onurakpolat/awesome-bigdata#73]
I would not have ever thought to classify Oracle Database, a traditional RDBMS, as NewSQL. Even with RAC, it still has a shared-everything architecture at the storage layer. Can you share your thoughts on including here?

**Comment by onurakpolat** [comment]
@davidlday thanks for sharing your thoughts. You're right - I agree. There is currently no **RDBMS** section, should we add one?

**Comment by onurakpolat** [comment]
https://github.com/onurakpolat/awesome-bigdata/blob/master/README.md#rdbms

:+1:

**Comment by davidlday** [comment]
@onurakpolat - sorry I couldn't respond sooner. Yes, an RDBMS section feels appropriate and I like what you've added already! Not sure the scope of what this would cover but you can find some great info on databases in general at http://db-engines.com. Some of those might be worth adding here as well. Thanks for the changes!

**Comment by onurakpolat** [comment]
will look into it. Cheers!
