### ISSUE TITLE
May want to add ontological databases as well

### ISSUE THREAD

**Issue by mub** [onurakpolat/awesome-bigdata#94]
Also known as [&rarr;triplestores](https://www.w3.org/wiki/LargeTripleStores) - those are separate category and also scale to up to tera.

**Comment by cuent** [comment]
I am agree. I think triple stores should be added in a new category. 

Accumulo is been used as a base for some triple stores. IMHO, there is apache marmotta, parliament, fuseki, and strabon as I know so far. The endpoints are used to query the web, so it should be added to the list of Big Data.

**Comment by onurakpolat** [comment]
Would be great if you can prepare a PR, happy to review it!
